version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
      #- SSH_LISTEN_PORT=222
      - SSH_PORT=${SSH_PORT}
      #- HTTP_PORT=3001
      - GITEA__mailer__ENABLED=${GITEA__mailer__ENABLED}
      - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      - GITEA__mailer__MAILER_TYPE=${GITEA__mailer__MAILER_TYPE}
      - GITEA__mailer__HOST=${GITEA__mailer__HOST}
      - GITEA__mailer__IS_TLS_ENABLED=${GITEA__mailer__IS_TLS_ENABLED}
      - GITEA__mailer__USER=${GITEA__mailer__USER}
      - GITEA__mailer__PASSWD=${GITEA__mailer__PASSWD}
      - DOMAIN=${DOMAIN}
      - ROOT_URL=${ROOT_URL}
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ${VOLUME_DATA}:/data
      - ${VOLUME_TIMEZONE}:${VOLUME_TIMEZONE}:ro
      - ${VOLUME_LOCALTIME}:${VOLUME_LOCALTIME}:ro
    ports:
      - "${PORT_3000}:3000"
      - "${PORT_22}:22"
    depends_on:
      - db
      
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${GITEA__database__USER}
      - MYSQL_PASSWORD=${GITEA__database__PASSWD}
      - MYSQL_DATABASE=${GITEA__database__NAME}
    networks:
      - gitea
    volumes:
      - ${VOLUME_DATABASE}:${VOLUME_DATABASE2}